site_name: Pratham Kamble
nav:
    - Home: index.md
    - Projects: 
      - "Zaika: A Food Ordering App" : zaika.md
      - "Food Fiesta: Landing Website" : ff.md
      - "LearnSBAR: Training Platform" : learnsbar.md
      - "Instacart Reorder Prediction" : instacart.md
      - "Udemy Enrollment Prediction" : udemy.md
      - "SLT: Social Listening Tool" : slt.md
      - "AI Competitor Intelligence Tool": competitor.md
      - "Real Time Object Detection": real_time_object_detection.md
      - "Azure Data Lake + ETL Pipeline": azure_data_lake_etl.md
    - Contact Me: contact.md
theme:
  name: material
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode

  features:
    - content.code.annotate 
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 



plugins:
  - glightbox
  - mkdocs-video
  - mkdocs-pdf
